from django.urls import path
from . import views
from django.views.generic import RedirectView

app_name = 'persona'

urlpatterns = [
    path('get/images/', views.get_image_ajax, name="get-images"),
    path('get/images/liked/', views.get_image_ajax_liked, name="get-images-liked"),
    path('get/images/tags/', views.get_image_ajax_tags, name="get-images-tags"),
    path('get/image/detail', views.get_image_detail, name="get-image-detail"),
    path('tag/<str:tag_slug>/', views.tags, name="tag"),
    path('about/', views.about, name="about"),
    path('delete/comment/it/', views.delete_comment_it, name="delete-comment-it"),
    path('comment/it/', views.comment_it, name="comment-it"),
    path('new/profile/', views.new_profile, name="new-profile"),
    path('delete/account/', views.delete_account, name="delete-account"),
    path('change/passoword/', views.change_password, name="change-password"),
    path('notifications/', views.notifications, name="notifications"),
    path('', views.index, name="index"),
    path('post/<int:post_id>/', views.detail, name="detail"),
    path('signup/', views.signup_form, name="signup"),
    path('login/', views.login_form, name="login"),
    path('logout/', views.logout_form, name="logout"),
    path('edit/profile/', views.edit_profile, name="edit-profile"),
    path('my/profile/', views.my_profile, name="my-profile"),
    path('profile/<int:user_id>/', views.profile, name="profile"),
    path('add/image/', views.add_image, name="add-image"),
    path('add/video/', views.add_video, name="add-video"),
    path('add/audio/', views.add_audio, name="add-audio"),
    path('add/text/', views.add_text, name="add-text"),
    path('add/link/', views.add_link, name="add-link"),
    path('add/youtube/', views.add_youtube, name="add-youtube"),
    path('add/instagram/', views.add_insta, name="add-insta"),
    path('search/', views.search, name="search"),
    path('edit/post/<int:post_id>/', views.edit_post, name="edit-post"),
    path('delete/post/<int:post_id>/', views.delete_post, name="delete-post"),
    path('likeit/', views.like_post_it, name="likeit"),
    path('comment/<int:post_id>/', views.comment_post, name="comment"),
    path('delete/comment/<int:comment_id>/<int:post_id>/', views.delete_comment, name="delete-comment"),
    path('explore/', views.explore, name="explore"),
    path('liked/posts/', views.liked_posts, name="liked-posts"),
    path('follow/js/', views.follow_it, name="follow-it"),
    path('gmail/', views.share_gmail, name="gmail"),
    path('post/<int:post_id>/comments/', views.go_to_detail, name="comments-detail"),
    path('post/<int:post_id>/likes/', views.go_to_detail, name="likes-detail"),
    path('post/<int:post_id>/share/', views.go_to_detail, name="share-detail"),
    path('add/posts/', RedirectView.as_view(url="/")),
    path('profile/<int:user_id>/following/', views.go_to_profile, name="following-profile"),
    path('profile/<int:user_id>/followers/', views.go_to_profile, name="followers-profile"),
    path('my/profile/following/', views.go_to_my_profile, name="my-following-profile"),
    path('my/profile/followers/', views.go_to_my_profile, name="my-followers-profile"),
]
